//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWebGreeting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Account_Info = new HashSet<Account_Info>();
            this.Payments = new HashSet<Payment>();
            this.Sendings = new HashSet<Sending>();
        }
    
        public string username { get; set; }
        public string password { get; set; }
        public string question { get; set; }
        public string answer { get; set; }
        public Nullable<int> roldId { get; set; }
    
        public virtual ICollection<Account_Info> Account_Info { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<Sending> Sendings { get; set; }
    }
}
