//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWebGreeting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Greeting
    {
        public Greeting()
        {
            this.Sendings = new HashSet<Sending>();
        }
    
        public int id { get; set; }
        public string contents { get; set; }
        public string tittle { get; set; }
        public string customMessenger { get; set; }
        public byte[] photo { get; set; }
        public Nullable<int> categoryID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Sending> Sendings { get; set; }
    }
}
