//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWebGreeting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sending
    {
        public int greetingId { get; set; }
        public string usernameId { get; set; }
        public string senderName { get; set; }
        public string rersiveName { get; set; }
        public string addressTo { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Greeting Greeting { get; set; }
    }
}
